export interface Product {
    _id: string,
    internalCode: string,
    productName: string,
    description: string,
    barCode: number,
    category: string,
    subCategory: string,
    brand: string,
    avatarUrl: string,
    warranty: number,
    price: number,
    aditionals: number,
    tax: number,
    markup: number,
    minStock: number,
    onlineMarket: boolean,
    deleted: boolean,
    serialNumberRequired: boolean,
}